accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^signup/$', views.signup_view, name="signup"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	url('avatar/', include('avatar.urls')),
]

articles/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='articles'

urlpatterns = [
    path('/',views.articles_list, name="list"),
    url(r'^create/$',views.articles_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details, name="detail"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from slider import views as sl

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('about/', views.about),
    path(r'', sl.slider_list, name="home"),
    path('avatar/', include('avatar.urls')),
    #path('', include('slider.urls'), name="home"),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

slider/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='slider'

urlpatterns = [
    url(r'^$',views.slider_list, name="slide"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
     
class UserProfile(models.Model):
	home_address = models.TextField()
	#phone_numer = models.PhoneNumberField()
	user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	# add in thumbnail later
	thumb = models.ImageField(default = 'default.png', blank=True)
	# add in author later
	author = models.ForeignKey(User, on_delete=models.CASCADE, default = None)
	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:40] + '...'

category/models.py
from django.db import models
from django.contrib.auth.models import User
     
# Create your models here.
class Category(models.Model):
	MANAGER = 'Manager'
	MECHANIC = 'Mechanic'
	ELEC = 'Electrical'
	SPON = 'Spon'
	UNKNOW = 'unknown'
	CHOICES = ((MANAGER, 'Manager'),(MECHANIC, 'Mechanic'),(ELEC, 'Electrical'),(SPON, 'S.M.L'),(UNKNOW, 'unkown'))
	#phone_numer = models.PhoneNumberField()
	user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)
	category = models.CharField(max_length=20, choices=CHOICES, default=SPON)
	is_leader = models.CharField(max_length=20, choices=CHOICES, default=UNKNOW)
    
	def __str__(self):
		return self.user.username

comments/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Comment(models.Model):
	owner = models.CharField(max_length=100)
	comment = models.TextField()
	# add in thumbnail later
	thumb = models.ImageField(default = 'default.png', blank=True)
	# add in author later
	def __str__(self):
		return self.owner

logos/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Logo(models.Model):
	name = models.CharField(max_length=100)
	url = models.CharField(max_length=100)
	thumb = models.ImageField(default = 'default.png', blank=True)
	# add in author later
	def __str__(self):
		return self.name

slider/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Slider(models.Model):
	title = models.CharField(max_length=100)
	title2 = models.CharField(max_length=100)
	# add in thumbnail later
	thumb = models.ImageField(default = 'default.png', blank=True)
	# add in author later
	def __str__(self):
		return self.title

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })


def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log
			user = form.get_user()
			login(request, user)
			if 'next' in request.POST:
				return redirect(request.POST.get("next"))
			else:
				return redirect('/')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html',{ 'form':form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('/')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def articles_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request,'articles/articles_list.html',{'articles': articles})

def article_details(request, slug):
	#return HttpResponse(slug)
	article = Article.objects.get(slug = slug)
	return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url = "/accounts/login")
def articles_create(request):
	if request.method == 'POST':
		form = forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			# save article to db
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')
	else:
		form = forms.CreateArticle()
	return render(request, 'articles/article_create.html', {'form': form})	

category/views.py
from django.shortcuts import render

# Create your views here.

comments/views.py
from django.shortcuts import render

# Create your views here.

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
	#return HttpResponse('homepage')
	return render(request,'homepage.html')

def about(request):
	#return HttpResponse('about')
	return render(request,'about.html')

logos/views.py
from django.shortcuts import render

# Create your views here.

slider/views.py
from django.shortcuts import render, redirect
from .models import Slider
from articles.models import Article
from category.models import Category
from comments.models import Comment
from logos.models import Logo

from django.http import HttpResponse
# Create your views here.

def slider_list(request):
	articles = Article.objects.all().order_by('date')
	category = Category.objects.all()
	comments = Comment.objects.all()
	logos = Logo.objects.all()
	slider = Slider.objects.all()
	return render(request,'articles/articles_list.html',{'slider': slider, 'articles': articles, 'category': category, 'comments': comments, 'logos': logos})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
	{% csrf_token %}
	{{ form }}
	{% if request.GET.next %}
		<input type="hiden" name="next" value="{{request.GET.next}}">
	{% endif %}
	<input type="submit" name="Login">
</form>
</div>
&nbsp
{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="Signup">
</form>
</div>
&nbsp
{% endblock%}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}


{% block content%}
<div class="container">
	<div class="create-article">
		<h2> Create an Awsome New Article</h2>
		<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{form}}
			<input type="submit" name="Create">
		</form>
	</div>
	<script type="text/javascript" src="/static/slugify.js"></script>
</div>
&nbsp
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% load avatar_tags %}
{% load static from staticfiles %}


{% block content%}

<div class="article-detail">
	<div class="article">
		<section id="global-header">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="block text-center">
							<h1>BIG HEADLINE FOR BLOG</h1>
							<p>{{ article.date }} / By {{ article.author }}</p>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section id="blog-left">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-0 col-sm-10 col-sm-offset-1">
						<div class="blog-img row">
							<div class="col-md-12">
								<img class="img-responsive" src="{{ article.thumb.url }}" alt="">
							</div>
						</div>
						<div class="block">
							<span class="first-child-span">{{ article.title }}</span>
							<p class="first-child">{{ article.body }}</p><br>
							<div class="tags">
								<h5>Tags</h5>
								<a href="#">Advertisement</a>,
								<a href="#">Smart Quotes</a>,
								<a href="#">Unique</a>,
								<a href="#">Design</a>
							</div>
							<div class="blog-comment">
								<a class="comment-img" href="#">
									{% avatar article.author %}
								</a>
								<div class="comment-text">
									<h5>
										<a href="#">About The Author</a>
									</h5>
									<span>{{ article.author }}</span>
								</div>
							</div>
							<!-- social media icon -->
							<div class="media-link">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-md-offset-1 col-sm-4">
						<div class="widget">
							<form>
								<i class="fa fa-search"></i>
								<input type="text" name="search" class="" placeholder="TYPE KEYWORD HERE...">
							</form>
						</div>
						<div class="widget">
							<span>Categories</span>
							<div class="widget-body">
								<ul class="category-list">
								    <li><a href="#">Web Design</a></li>
								    <li><a href="#">Featured Blog</a></li>
								    <li><a href="#">Photography Idea</a></li>
								    <li><a href="#">Design Tutorials</a></li>
								    <li><a href="#">News and Events</a></li>
								    <li><a href="#">Arts and Entertainment</a></li>
								</ul>
							</div>
						</div>
						<div class="widget">
							<span>ABOUT ME</span>
							<div class="widget-body">
								<img class="img-responsive" src="{% static 'img/blog-img8.jpg' %}" alt="">
								<span class="title">JOHN DEO</span>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been industry's standard.</p>
							</div>
						</div>
						<div class="widget">
							<span>TEXT WIDGET</span>
							<div class="widget-body">
								<p>Lorem Ipsum is simply dummy text of printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the of type and scrambled it to make a type specimen.</p>
							</div>
						</div>
						<div class="widget">
							<span>POPULAR POSTS</span>
							<div class="widget-body">
								<ul class="category-list">
								    <li><a class="items" href="#">Standard Post with Gallery</a>Saturday - June 15, 2013</li>
								    <li><a class="items" href="#">Standard post with preview Video</a>Saturday - June 20, 2013</li>
								    <li><a class="items" href="#">Standard post with preview Picture</a>Saturday - June 25, 2013</li>
								    <li><a class="items" href="#">Standard Post with Gallery</a>Saturday - June 15, 2013</li>
								</ul>
							</div>
						</div>
						<div class="widget sidebar-tags">
							<span>Tags</span>
							<div class="widget-body">
								<a href="#">Advertisement</a>
								<a href="#">Fashion</a>
								<a href="#">Sea</a>
								<a href="#">Forest</a>
								<a href="#">Nature</a>
								<a href="#">Portrait</a>
								<a href="#">Wordpress</a>
								<a href="#">Photo</a>
								<a href="#">Sky</a>
							</div>
						</div>
						<div class="widget">
							<span>RECENT COMMENTS</span>
							<div class="widget-body">
								<ul class="category-list">
								    <li><a href="#">Standard Post with Gallery</a>Saturday - June 15, 2013</li>
								    <li><a href="#">Standard post with preview Video</a>Saturday - June 20, 2013</li>
								    <li><a href="#">Standard post with preview Picture</a>Saturday - June 25, 2013</li>
								    <li><a href="#">Standard Post with Gallery</a>Saturday - June 15, 2013</li>
								</ul>
							</div>
						</div>
						<div class="widget">
							<a href="#">
								<img class="img-responsive" src="{% static 'img/blog-img7.jpg' %}" alt="">
							</a>
						</div>
					</div>
			
				</div>
			</div>
		</section>
	</div>	
</div>

{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>about page</title>
</head>
<body>
	<h1>this an about page</h1>
	<p>nigga is the n-word</p>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}
{% load avatar_tags %}

<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hercules</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- google fonts -->

        <!-- Css link -->
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/preloader.css' %}">
        <link rel="stylesheet" href="{% static 'css/image.css' %}">
        <link rel="stylesheet" href="{% static 'css/icon.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />  
        <script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.3"></script>

    </head>
    <body id="top" onload="LoadMap();">
        <header id="navigation" class="navbar-fixed-top animated-header">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    
                    <a href="{% url 'home' %}"><img src="{% static 'img/logo3.png' %}" height="80" width="200" style="margin-top: -10px; margin-left: -50px " alt=""></a>
                    
                    <!-- /logo -->
                </div>
                <form id="formname" class="logout-link" action="{% url 'accounts:logout' %}" method="post">         
                    {% csrf_token %}
                </form>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <ul id="nav" class="nav navbar-nav menu" >
                    {% if user.is_authenticated %}
                        <li><a href="#features">competions</a></li>
                        <li><a href="#counter">specifications</a></li>
                        <li><a href="#portfolio">Membres</a></li>
                        <li><a href="#team">Team Leaders</a></li>
                        <li><a href="#pricing-table">Packages</a></li>
                        <li><a href="#blog">Blog</a></li>
                        <li><a href="#testimonial">Opinions</a></li>
                        <li><a href="#contact-form">Contact</a></li>
                        <div class="dropdown" >
                        <li><a href="#" class="not-active" style="margin-left: 10px">Operations</a></li>
                            <div class="dropdown-content">
                                <li><a href="{% url 'avatar_change' %}">{% avatar user.username 65 class="img-circle img-responsive" %}  {{ user.username }} </a></li>
                                <li><a href="{% url 'articles:create' %}" class="highlight">New Artice</a></li>
                                <li><a href="#" onclick="document.getElementById('formname').submit()">Logout</a></li>
                            </div>
                        </div>
                    {% else %}
                        <li><a href="#features">competions</a></li>
                        <li><a href="#counter">specifications</a></li>
                        <li><a href="#portfolio">Membres</a></li>
                        <li><a href="#team">Team Leaders</a></li>
                        <li><a href="#pricing-table">Packages</a></li>
                        <li><a href="#blog">Blog</a></li>
                        <li><a href="#testimonial">Opinions</a></li>
                        <li><a href="#contact-form">Contact</a></li>
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                    {% endif %}
                <!-- /main nav -->
                    </ul>
                </nav>
            </div>
        </header>


        <div class="wrapper">
            {% block content %}

            {% endblock %}
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <a href="#"><img src="{% static 'img/logo3.png' %}" alt="" style="width: 400px;height: 150px;"></a>
                            <p>© 2018 All rights reserved <a href="https://www.facebook.com/HerculesCarfstt/" target="_blank">HJercules Team</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

        <!-- load Js -->
        <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>
        <script src="{% static 'js/waypoints.min.js' %}"></script>
        <script src="{% static 'js/lightbox.js' %}"></script>
        <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/html5lightbox.js' %}"></script>
        <script src="{% static 'js/jquery.mixitup.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/jquery.scrollUp.js' %}"></script>
        <script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/jquery.nav.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script type="text/javascript">
            function loadMap(){ 
                if(typeof(VEMap) === 'undefined'){
                    setTimeout(loadMap, 150);
                    return;
                }

                map = new VEMap('map');
                map.SetCredentials("BingMapsKey"); 
                mapCenter= new VELatLong(51.8756, -97.9956)
            }
        </script>
    </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Homepage</title>
</head>
<body>
	<h1>This is a Homepage</h1>
	<p>can the lkabir say the n-word</p>
</body>
</html>